name: workflow
on:  
  push:
    branches:
      - main
      - uat
      - dev
jobs:
  build_dev:
    if: ${{ github.ref == 'ref/heads/dev' }}
    uses: ./.github/workflows/reuseworkflow.yml
    with:
      branch: "main"
      name_space:  "main"
    secrets: inherit
  build_uat:
    if:  ${{ github.ref == 'ref/heads/uat' }}
    uses: ./.github/workflows/reuseworkflow.yml
    with:
      branch: "main"
      name_space:  "main"
    secrets: inherit
  build_main:
    if:   ${{ github.ref == 'ref/heads/main' }}
    uses: ./.github/workflows/reuseworkflow.yml
    with:
      branch: "main"
      name_space: "main"
    secrets: inherit
