name: build_deploy_aks

on:
  workflow_call:
    inputs:
      name_space: 
        required: true
        type: string
      branch: 
        required: true
        type: string
env:
  AZURE_CONTAINER_REGISTRY: "metacrew2023"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "metacrew-dev2"
  CLUSTER_NAME: "dev-aks"
  CHART_PATH: "your-chart-path"
  CHART_OVERRIDE_PATH: "your-chart-override-path"

jobs:
  buildImage:
    runs-on: 
      labels: linux
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: test
        run: |
            cat ${{ github.event.inputs.branch }}/${{ github.event.inputs.branch }}.yaml
      # - name: ACR build
      #   id: build-push-acr
      #   uses: azure/acr-build@v1
      #   with:
      #     service_principal: ${{ secrets.service_principal }}
      #     service_principal_password: ${{ secrets.service_principal_password }}
      #     tenant: ${{ secrets.tenant }}
      #     registry: ${{ secrets.registry }}
      #     repository: ${{ secrets.repository }}
      #     image: azure-vote-front
      #     folder: azure-vote
      #     branch: ${{ github.event.inputs.branch }}
      #     tag: ${{ github.sha }}
      #     git_access_token: ${{ secrets.git_access_token }}
      #     # git_url: https://github.com/websolution625/webapp-aks.git