name: build_deploy_aks

on:
  workflow_call:
    inputs:
      name_space: 
        required: true
        type: string
      branch: 
        required: true
        type: string
env:
  AZURE_CONTAINER_REGISTRY: "metacrew2023"
  CONTAINER_NAME: "your-container-name"
  RESOURCE_GROUP: "metacrew-dev2"
  CLUSTER_NAME: "dev-aks"
  CHART_PATH: "your-chart-path"
  CHART_OVERRIDE_PATH: "your-chart-override-path"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    env: 
      BRANCH: ${{inputs.branch }}
    runs-on: 
      labels: linux
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: test
        run: |
            cat ${{env.BRANCH}}/${{env.BRANCH}}.yaml
      - name: test secret
        id: build-push-acr
        uses: ./.github/workflows/secret.yml
        with:       
          service_principal_workflow: ${{ secrets.service_principal }}
          service_principal_password_workflow: ${{ secrets.service_principal_password }}
          tag_workflow: ${{ github.sha }}
          git_access_token_workflow: ${{ secrets.git_access_token }}
      - name: showsecret
        run: |
            echo  "${{ secrets.service_principal }}" >> test.txt
            echo  "${{ secrets.service_principal_password }}" >> test.txt
            echo  "${{ github.sha }}" >> test.txt
            echo  "${{ github.git_access_token }}" >> test.txt
            cat test.txt
            rm -rf test.txt          