name: build_secret

on:
  workflow_call:

    secrets:
      service_principal_workflow:
        required: true
      service_principal_password_workflow:
        required: true
      tag_workflow:
        required: true
      git_access_token_workflow:
        required: true          
jobs:
  secrettest:
    permissions:
      contents: read
      id-token: write
    runs-on: 
      labels: linux
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: showsecret
        run: |
            echo  "${{ secrets.service_principal }}" >> test.txt
            echo  "${{ secrets.service_principal_password }}" >> test.txt
            echo  "${{ github.sha }}" >> test.txt
            echo  "${{ github.git_access_token }}" >> test.txt
            cat test.txt
            rm -rf test.txt
      - name: showsecret_workflow
        run: |
            echo  "${{ secrets.service_principal_workflow }}" >> test1.txt
            echo  "${{ secrets.service_principal_password_workflow }}" >> test1.txt
            echo  "${{ github.tag_workflow }}" >> test1.txt
            echo  "${{ github.git_access_token_workflow }}" >> test1.txt
            cat test1.txt
            rm -rf test1.txt