name: build_secret

on:
  workflow_call:
         
jobs:
  secrettest:
    permissions:
      contents: read
      id-token: write
    runs-on: 
      labels: linux
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: showsecret
        run: |
            echo  "${{ secrets.service_principal }}" >> test.txt
            echo  "${{ secrets.service_principal_password }}" >> test.txt
            echo  "${{ github.sha }}" >> test.txt
            echo  "${{ github.git_access_token }}" >> test.txt
            cat test.txt
            rm -rf test.txt